version: "3.6"
services:
  minisatip:
    image: lscr.io/linuxserver/minisatip
    container_name: minisatip
    network_mode: host
    environment:
      - PUID=0
      - PGID=0
      - TZ=Europe/Vienna
      - RUN_OPTS=--satip-xml http://192.168.1.100:8000/description.xml -w 192.168.178.22:8875 -E # FWD SatIP UDP WAN2 -> DMZ
    volumes:
      - ./config:/config
    restart: always
