# - alias: Irrigation check
#   initial_state: true
#   trigger: 
#     - platform: template
#       value_template: "{{ states.sensor.time.state == states.input_datetime.irrigation_check.state[0:5] }}"
#   condition:
#     # If today's forecast shows no rain, continue
#     - condition: numeric_state
#       entity_id: 'sensor.dark_sky_precip_intensity_0d'
#       below: 0.5
#     # If tomorrow's forecast shows no rain, continue
#     - condition: numeric_state
#       entity_id: 'sensor.dark_sky_precip_intensity_1d'
#       below: 0.5
#     - condition: state
#       entity_id: 'input_boolean.rained_yesterday'
#       state: "off"
#   action:
#     service: input_boolean.turn_on
#     entity_id: input_boolean.irrigation_scheduled
    
# - alias: Irrigation turn on
#   initial_state: true
#   trigger: 
#     - platform: template
#       value_template: "{{ states.sensor.time.state == states.input_datetime.irrigation_time.state[0:5] }}"
#   condition:
#     - condition: state
#       entity_id: 'input_boolean.irrigation_scheduled'
#       state: "on"
#   action:
#     service: homeassistant.turn_on
#     entity_id: switch.irrigation_schedule
    
- alias: Irrigation turn off (too long)
  trigger: 
    - platform: state
      entity_id: switch.irrigation_manual
      to: "on"
      for:
        hours: 1
  condition:
    - condition: state
      entity_id: switch.irrigation_manual
      state: "on"
  action:
    service: homeassistant.turn_off
    entity_id: switch.irrigation_manual
    
- alias: Irrigation set _yesterday for today
  trigger: 
    - platform: time
      at: "16:00:00"
  condition:
    - condition: template
      value_template: "{% if is_state('sensor.dark_sky_precip_0d', 'rain') %}true{% endif %}"
    - condition: numeric_state
      entity_id: 'sensor.dark_sky_precip_intensity_0d'
      above: 0.5
  action:
    service: input_boolean.turn_on
    entity_id: input_boolean.rained_yesterday
      
- alias: Irrigation default off
  trigger: 
    - platform: time
      at: "15:00:00"
  action:
    - service: input_boolean.turn_off
      entity_id: input_boolean.irrigation_scheduled
    - service: input_boolean.turn_off
      entity_id: input_boolean.rained_yesterday
      
